# Site settings
title: Anik Halder
description: Postdoctoral Research Associate at the Institute of Astronomy, University of Cambridge

author:
  name: Anik Halder
  email: "[firstname].[lastname] [at] ast.cam.ac.uk"
  
# Build settings
remote_theme: jekyll/minima

minima:
  skin: classic
  
